events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/json;

    server {
        listen 80;
        server_name localhost;

        location /users {
            alias /usr/share/nginx/html/users;
            autoindex on;
            autoindex_format json;
        }

        location /health {
            return 200 '{"status":"ok"}';
            add_header Content-Type application/json;
        }
    }
}
